name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, "unverified"]
assignees:
  - Peperehobbit01
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Also tell us, what did you expect to happen?
      description: Tell us what you see!
      placeholder: 
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a way to reproduce the problem or at list what you did before getting it.
      placeholder: 
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: System
      description: Please select the system that the reported issue pertains to.
      options:
        - "Giveaway System"
        - "Information System"
        - "Modération System"
        - "Ticket System"
        - "Logs System"
        - "Other components of the software"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - Stable = realesed on the realesed Github pages as Stable.
        - Canary = realesed on the realesed Github pages as PreRelease.
        - Dev = donwloaded the latest version of the main branch.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MultivetisMc/MultivetisMc-bot/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
